### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by xApep** [pratinav/jCider#2]
Some demo would be nice ;)

**Comment by pratinav** [comment]
Hi @xApep, just switched websites a while back, a demo should be up on the new website soon.

**Comment by pratinav** [comment]
Added a demo to the [homepage](https://pratinav.xyz/jCider/). Looks ugly, but will do.
closes #2

**Comment by pratinav** [comment]
Added a demo to the [homepage](https://pratinav.xyz/jCider/). Kinda ugly, but will do.
